[package]
name = "prcn_lib"
version = "0.1.0"
authors = ["Loptall <yutapypy0930@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
proconio = { version = "0.3.6", features = ["derive"]  }