[package]
name = "prcn_lib"
version = "0.2.2"
authors = ["Loptall <yutapypy0930@gmail.com>"]
edition = "2018"
license = "MIT"
description = "private library for atcoder"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = { version = "0.3.6", features = ["derive"]  }
rand = "0.7.3"